#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "7240568646:AAGQotVB37QakeoN663K85cFfl1ktfPcQaA")
    API_ID = int(os.environ["API_ID", 25891183]
    API_HASH = os.environ["API_HASH", "36709c81d7609a81f86de931cbc87f3a"]
    AUTH_USERS = "6674754789"""


# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/Stubborn1223 ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
